### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by AuspeXeu** [fphammerle/docker-radicale#51]
When running your image with the following compose entry
```
radicale:
  image: fphammerle/radicale
  hostname: radicale
  container_name: radicale
  ports:
    - 5232:5232
  volumes:
    - ./radicale/config:/etc/radicale/config:ro
    - ./radicale/users:/etc/radicale/htpasswd:ro
    - ./radicale-data:/var/lib/radicale/collections:rw
  restart: "unless-stopped"
```
I get the following permissions problem
```
[2023-04-24 14:21:07 +0000] [1/Thread-3] [ERROR] An exception occurred during PROPFIND request on '/': [Errno 13] Permission denied: '/var/lib/radicale/collections/.Radicale.lock'
```
